name: build-docs
on:
  push:
    tags:
      - 'v*'
jobs:
  build-docs:
    name: build-docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Build docs.yml
        uses: sudo-bot/action-doctum@v5
        with:
          config-file: doctum.dist.php
          method: "update"
          cli-args: "--output-format=github --no-ansi --no-progress -v"

      - name: Commit doc changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Publish docs.yml"
          file_pattern: "docs.yml/*"
          add_options: "-f"
          skip_dirty_check: true
